#!/usr/bin/perl -CSDAL

use warnings; 
use strict;
use File::Slurp::Unicode;
use IServ::DB;
use NetAddr::MAC;
use Time::HiRes qw(gettimeofday tv_interval);

my @uniquelocal_prefixes = sort split "\n", qx(netquery6 --uniquelocal --format "nic prefix");

sub print_time($$)
{
  my ($mod, $time) = @_;
  printf "$mod: %.0fms\n", tv_interval($time) * 1000;
}

# dhcp
{
  my $out;
  my $moduletime = [gettimeofday];

  for (@{ DBH->selectall_arrayref("SELECT Name, MAC ".
    "FROM hosts WHERE MAC IS NOT NULL ORDER BY Name") or die $! })
  {
    my ($name, $mac) = @$_;

    for my $prefix (sort @uniquelocal_prefixes)
    {
      my ($nic, $net) = split " ", $prefix;

      # strip double : at end
      my $ip_net = substr $net, 0, -2;
      my $mac_converter = new NetAddr::MAC $mac;
      my $ip = $ip_net . ":" . as_ipv6_suffix $mac_converter;

      my @content;
      undef @content;
      @content = @{ $out->{$nic} } if defined $out->{$nic};
      @content = () if not @content;

      push @content, "host $name-$nic {\n";
      push @content, "  hardware ethernet $mac;\n";
      push @content, "  fixed-address6 $ip;\n";
      push @content, "}\n";

      $out->{$nic} = \@content;
    }
  }

  for my $nic (sort keys %$out)
  {
    write_file "/var/lib/iserv/config/dhcpd6.conf.$nic.hosts", @{ $out->{$nic} };
  }

  system "/etc/init.d/isc-dhcp-server6", "restart", "&>/dev/null", "&";
  print_time("update dhcp", $moduletime);
}
