#!/usr/bin/perl -CSDAL
use warnings;
use strict;
use IServ::DB;
use IServ::Conf;

# run asynchronously
fork and exit;
open STDIN, "/dev/null" or die $!;
open STDOUT, ">/dev/null" or die $!;
open STDERR, ">/dev/null" or die $!;

my ($act, $ip) = @ARGV;

if ($conf->{UseDHCPv6})
{
  winexe $ip, netlogon "ipv6-enable-randomize-identifier.bat";
}
else
{
  winexe $ip, netlogon "ipv6-disable-randomize-identifier.bat";
}

