#!/bin/bash -e

. /usr/lib/iserv/cfg

for net in ${LANInterfaces[@]}
do
  grep -q "^$net"'$' /var/lib/iserv/config/ipv6-dhcp-interfaces.list && continue
  grep "iface $net inet6 dhcp" /etc/network/interfaces.d/ipv6 && continue
  [ -f "/var/lib/iserv/ipv6-support/ula/${net}.uln" ] || exit 1
done

