#!/bin/bash

# LAN-Ranges durch Kommata getrennt, sodass sie z. B. iptables -s übergeben
# werden können
LAN_SPEC=""
for l in $(netquery6 --lan --global --format prefix/length)
do
  if [[ "$l" =~ ':' ]]
  then
    if ! [ -z "$LAN_SPEC" ]
    then
      LAN_SPEC+=","
    fi
    LAN_SPEC+="$l"
  fi
done

# Interface zum Internet bestimmen
DEFIF="$(LC_ALL=C ip -6 route show default | awk '$1=="default" {print $5}' | 
  sed 's/^ppp[0-9]\+/ppp+/')"

iptables_multidest()
{
  DOMAIN="$1"
  shift

  FN=/usr/share/iserv/security/iplist6/"$DOMAIN"

  if [ ! -r "$FN" ]
  then
    echo "$0: \"$FN\" not found!" >&2
    continue
  fi

  cat "$FN" | while read IP
  do
    iptables -d "$IP" "$@"
  done
}

# Zusätzliche Kernelmodule für problematische Protokolle laden
# Hinweis: Seit Kernel 2.6.20 heißen die Module intern nf_* statt ip_*.
#if [ -x /sbin/modprobe ]
#then
#  for proto in amanda ftp h323 irc pptp sip tftp
#  do
#    if ! lsmod | grep -q "^ip_nat_$proto \|^nf_nat_$proto "
#    then
#      modprobe ip_nat_$proto
#    fi
#  done
#fi
