#!/bin/bash -e

. /usr/lib/iserv/cfg

[ -z "$ExternalIPs" ] && exit 0

ERRORS=0

DEFIF="$(. /usr/lib/iserv/ipv6_defif)"

IPs="$(netquery6 -i "$DEFIF" -g "ip" | while read i
do
  perl -e 'use Net::IP; print Net::IP::ip_expand_address "$ARGV[0]", 6;' "$i"
  echo
done | sort)"
  
CURIPs="$(dig +short ipv6.$Domain AAAA @ns.iserv.eu 2> /dev/null | while read i
do
  perl -e 'use Net::IP; print Net::IP::ip_expand_address "$ARGV[0]", 6;' "$i"
  echo
done | sort)"

if ! [ -z "$IPs" ] && ! [ "$IPs" = "$CURIPs" ]
then
  if ! [ "$1" = "-r" ]
  then
    let ERRORS++
  fi

  if [ "$1" = "-r" ]
  then
    regdns -d "ipv6.$Domain. AAAA" > /dev/null

    for i in ${IPs[@]}
    do
      regdns -a "ipv6.$Domain. 300 AAAA $i" > /dev/null
    done
  fi
fi

IP="$(myip -4)"
CURIP="$(dig +short ipv4.$Domain A @ns.iserv.eu 2> /dev/null)"

if ! [ -z "$IP" ] && ! [ "$IP" = "$CURIP" ]
then
  if ! [ "$1" = "-r" ]
  then
    let ERRORS++
  fi

  if [ "$1" = "-r" ]
  then
    regdns -d "ipv4.$Domain. A" > /dev/null
    regdns -a "ipv4.$Domain. 300 A $IP" > /dev/null
  fi
fi

if [ $ERRORS -gt 0 ]
then
  exit 1
fi
