#! /bin/sh

### BEGIN INIT INFO
# Provides:             nat6
# Required-Start:       $local_fs $remote_fs $network $time postgresql radvd wide-dhcp-client nat
# Required-Stop:        $local_fs $remote_fs $network $time
# Should-Start:         $syslog
# Should-Stop:          $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    IServ Network Address Translation (IPv6)
### END INIT INFO

# Author: Felix Jacobi <felix.jacobi@iserv.eu>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="IServ Network Address Translation (IPv6)"
NAME=nat6
DAEMON=/etc/$NAME
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

reset_iptables()
{
  echo 0 > /proc/sys/net/ipv6/conf/all/forwarding

  # Kill everything except fail2ban, reset all policys to ACCEPT
  ip6tables-save |
    grep -E -e "^(\*|COMMIT|:\w+ \w+ )" \
         -e "^(:fail2ban-|-A INPUT .* -j fail2ban-|-A fail2ban-)" |
    sed 's/^\(:\w\+\) \w\+ /\1 ACCEPT /' |
    ip6tables-restore
}

#
# Function that starts the daemon/service
#
do_start()
{
	reset_iptables
	[ -f /etc/nat6 ] && /etc/nat6
}

#
# Function that stops the daemon/service
#
do_stop()
{
	reset_iptables
}

case "$1" in
  start|restart|force-reload)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
                0) log_end_msg 0 ;;
                1) log_progress_msg "(already running)" && log_end_msg 0 ;;
                2) log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
                0) log_end_msg 0 ;;
                1) log_progress_msg "(not running)" && log_end_msg 0 ;;
                2) log_end_msg 1 ;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
